%% Author: Bishwamoy Sinha Roy

%%
clear;
im_cbm = imread('../data/model_chickenbroth.jpg');
im_cb1 = imread('../data/chickenbroth_01.jpg');
im_cb2 = imread('../data/chickenbroth_02.jpg');
im_cb3 = imread('../data/chickenbroth_03.jpg');
im_cb4 = imread('../data/chickenbroth_04.jpg');
im_cb5 = imread('../data/chickenbroth_05.jpg');
im_inL = imread('../data/incline_L.png');
im_inR = imread('../data/incline_R.png');
im_desk = imread('../data/pf_desk.jpg');
im_floor = imread('../data/pf_floor.jpg');
im_floor_rot = imread('../data/pf_floor_rot.jpg');
im_pile = imread('../data/pf_pile.jpg');
im_scan_scaled = imread('../data/pf_scan_scaled.jpg');
im_stand = imread('../data/pf_stand.jpg');

im_cbm = im2double(rgb2gray(im_cbm));
im_cb1 = im2double(rgb2gray(im_cb1));
im_cb2 = im2double(rgb2gray(im_cb2));
im_cb3 = im2double(rgb2gray(im_cb3));
im_cb4 = im2double(rgb2gray(im_cb4));
im_cb5 = im2double(rgb2gray(im_cb5));
im_inL = im2double(rgb2gray(im_inL));
im_inR = im2double(rgb2gray(im_inR));
im_desk = im2double(rgb2gray(im_desk));
im_floor = im2double(rgb2gray(im_floor));
im_floor_rot = im2double(rgb2gray(im_floor_rot));
im_pile = im2double(rgb2gray(im_pile));
im_scan_scaled = im2double(im_scan_scaled);
im_stand = im2double(rgb2gray(im_stand));

[l_d, d_d] = briefLite(im_desk);
[l_f, d_f] = briefLite(im_floor);
[l_fr, d_fr] = briefLite(im_floor_rot);
[l_p, d_p] = briefLite(im_pile);
[l_ss, d_ss] = briefLite(im_scan_scaled);
[l_s, d_s] = briefLite(im_stand);
m_dd = briefMatch(d_d, d_d);
m_df = briefMatch(d_d, d_f);
m_dfr = briefMatch(d_d, d_fr);
m_dp = briefMatch(d_d, d_p);
m_dss = briefMatch(d_d, d_ss);
m_ds = briefMatch(d_d, d_s);
figure;
plotMatches(im_desk, im_desk, m_dd, l_d, l_d);
figure;
plotMatches(im_desk, im_floor, m_df, l_d, l_f);
figure;
plotMatches(im_desk, im_floor_rot, m_dfr, l_d, l_fr);
figure;
plotMatches(im_desk, im_pile, m_dp, l_d, l_p);
figure;
plotMatches(im_desk, im_scan_scaled, m_dss, l_d, l_ss);
figure;
plotMatches(im_desk, im_stand, m_ds, l_d, l_s);
figure;

[lm, dm] = briefLite(im_cbm);
[l1, d1] = briefLite(im_cb1);
[l2, d2] = briefLite(im_cb2);
[l3, d3] = briefLite(im_cb3);
[l4, d4] = briefLite(im_cb4);
[l5, d5] = briefLite(im_cb5);
m_mm = briefMatch(dm, dm);
m_m1 = briefMatch(dm, d1);
m_m2 = briefMatch(dm, d2);
m_m3 = briefMatch(dm, d3);
m_m4 = briefMatch(dm, d4);
m_m5 = briefMatch(dm, d5);
plotMatches(im_cbm, im_cbm, m_mm, lm, lm);
figure;
plotMatches(im_cbm, im_cb1, m_m1, lm, l1);
figure;
plotMatches(im_cbm, im_cb2, m_m2, lm, l2);
figure;
plotMatches(im_cbm, im_cb3, m_m3, lm, l3);
figure;
plotMatches(im_cbm, im_cb4, m_m4, lm, l4);
figure;
plotMatches(im_cbm, im_cb5, m_m5, lm, l5);
figure;

[ll, dl] = briefLite(im_inL);
[lr, dr] = briefLite(im_inR);
m = briefMatch(dl, dr);
plotMatches(im_inL, im_inR, m, ll, lr);
